name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Translation"
    labels:
      - "translation"
  - title: "Dependencies"
    labels:
      - "dependencies"
  - title: "Maintenance"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes
  $CHANGES
autolabeler:
  - label: "chore"
    files:
      - "*.md"
      - ".github/*"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
  - label: "minor"
    branch:
      - '/feature\/.+/'
  - label: "bugfix"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "translation"
    title:
      - "/translation/i"

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch