#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    # hass --config "${PWD}/config" --script ensure_config
    python3 -Xfrozen_modules=off -m homeassistant --config "${PWD}/config" --script ensure_config
fi

# Set the path to custom_components
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
#hass --config "${PWD}/config" --debug
python3 -Xfrozen_modules=off -m homeassistant --config "${PWD}/config" --debug