#!/usr/bin/env bash

# https://github.com/home-assistant/core
# https://github.com/MatthewFlamm/pytest-homeassistant-custom-component

# As of HA 2023.3, Python 3.11 is supported.
echo
pip3 install -qq homeassistant==2023.3.6 pytest-homeassistant-custom-component==0.13.10
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2023.4.6 pytest-homeassistant-custom-component==0.13.23
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2023.5.4 pytest-homeassistant-custom-component==0.13.32
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2023.6.3 pytest-homeassistant-custom-component==0.13.39
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2023.7.3 pytest-homeassistant-custom-component==0.13.45
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

# As of HA 2023.8, Python 3.10 is not supported.
echo
pip3 install -qq homeassistant==2023.8.4 pytest-homeassistant-custom-component==0.13.53
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed
