#!/usr/bin/env bash

# https://github.com/home-assistant/core
# https://github.com/MatthewFlamm/pytest-homeassistant-custom-component

run_first_test() {
  local asynciomode="$1"  # First parameter, "strict" or "auto"
  echo
  pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
  pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
  output=$(pytest -q --no-summary --asyncio-mode=$asynciomode tests 2>&1 | grep passed)
  echo "$output"
  number1=$(echo "$output" | awk '{print $1}')
  if [ -z "$number1" ]; then
    echo "No passed test cases!"
    exit 1
  fi
}

run_next_test() {
  local asynciomode="$1"  # First parameter, "strict" or "auto"
  echo
  pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
  pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
  output=$(pytest -q --no-summary --asyncio-mode=$asynciomode tests 2>&1 | grep passed)
  echo "$output"
  number2=$(echo "$output" | awk '{print $1}')
  if [ "$number1" != "$number2" ]; then
    echo "Results are different!"
    exit 1
  fi
}

# As of HA 2024.2, Python 3.12 is supported.
pip3 install -qq homeassistant==2024.2.4 pytest-homeassistant-custom-component==0.13.103
run_first_test "auto"

pip3 install -qq homeassistant==2024.3.3 pytest-homeassistant-custom-component==0.13.109
run_next_test "auto"

# As of HA 2024.4, Python 3.11 is not supported.

#pip3 install -qq homeassistant==2024.4.4 pytest-homeassistant-custom-component==0.13.115
#run_next_test "auto"
# Depends on non-existng version of mypy-dev

#pip3 install -qq homeassistant==2024.5.5 pytest-homeassistant-custom-component==0.13.125
#run_next_test "auto"
# Depends on non-existng version of mypy-dev

pip3 install -qq homeassistant==2024.6.4 pytest-homeassistant-custom-component==0.13.136
run_next_test "auto"

pip3 install -qq homeassistant==2024.7.4 pytest-homeassistant-custom-component==0.13.148
run_next_test "auto"

pip3 install -qq homeassistant==2024.8.3 pytest-homeassistant-custom-component==0.13.155
run_next_test "auto"

pip3 install -qq homeassistant==2024.9.3 pytest-homeassistant-custom-component==0.13.164
run_next_test "auto"

pip3 install -qq homeassistant==2024.10.4 pytest-homeassistant-custom-component==0.13.175
run_next_test "auto"

pip3 install -qq homeassistant==2024.11.3 pytest-homeassistant-custom-component==0.13.184
run_next_test "auto"

pip3 install -qq homeassistant==2024.12.5 pytest-homeassistant-custom-component==0.13.195
run_next_test "auto"


# As of HA 2025.2, Python 3.12 is not supported.