#!/usr/bin/env bash

# https://github.com/home-assistant/core
# https://github.com/MatthewFlamm/pytest-homeassistant-custom-component

run_first_test() {
  local asynciomode="$1"  # First parameter, "strict" or "auto"
  echo
  pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
  pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
  output=$(pytest -q --no-summary --asyncio-mode=$asynciomode tests 2>&1 | grep passed)
  echo "$output"
  number1=$(echo "$output" | awk '{print $1}')
  if [ -z "$number1" ]; then
    echo "No passed test cases!"
    exit 1
  fi
}

run_next_test() {
  local asynciomode="$1"  # First parameter, "strict" or "auto"
  echo
  pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
  pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
  output=$(pytest -q --no-summary --asyncio-mode=$asynciomode tests 2>&1 | grep passed)
  echo "$output"
  number2=$(echo "$output" | awk '{print $1}')
  if [ "$number1" != "$number2" ]; then
    echo "Results are different!"
    exit 1
  fi
}

# As of HA 2023.3, Python 3.11 is supported.
pip3 install -qq homeassistant==2023.3.6 pytest-homeassistant-custom-component==0.13.10
run_first_test "auto"

pip3 install -qq homeassistant==2023.4.6 pytest-homeassistant-custom-component==0.13.23
run_next_test "auto"

pip3 install -qq homeassistant==2023.5.4 pytest-homeassistant-custom-component==0.13.32
run_next_test "auto"

pip3 install -qq homeassistant==2023.6.3 pytest-homeassistant-custom-component==0.13.39
run_next_test "auto"

pip3 install -qq homeassistant==2023.7.3 pytest-homeassistant-custom-component==0.13.45
run_next_test "auto"

# As of HA 2023.8, Python 3.10 is not supported.
pip3 install -qq homeassistant==2023.8.4 pytest-homeassistant-custom-component==0.13.53
run_next_test "auto"
