#!/usr/bin/env bash

# https://github.com/home-assistant/core
# https://github.com/MatthewFlamm/pytest-homeassistant-custom-component

run_first_test() {
  local asynciomode="$1"  # First parameter, "strict" or "auto"
  echo
  pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
  pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
  output=$(pytest -q --no-summary --asyncio-mode=$asynciomode tests 2>&1 | grep passed)
  echo "$output"
  number1=$(echo "$output" | awk '{print $1}')
  if [ -z "$number1" ]; then
    echo "No passed test cases!"
    exit 1
  fi
}

run_next_test() {
  local asynciomode="$1"  # First parameter, "strict" or "auto"
  echo
  pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
  pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
  output=$(pytest -q --no-summary --asyncio-mode=$asynciomode tests 2>&1 | grep passed)
  echo "$output"
  number2=$(echo "$output" | awk '{print $1}')
  if [ "$number1" != "$number2" ]; then
    echo "Results are different!"
    exit 1
  fi
}

pip3 install -qq pytest-asyncio==0.20.2

pip3 install -qq homeassistant==2022.7.0 pytest-homeassistant-custom-component==0.10.2
run_first_test "strict"

pip3 install -qq homeassistant==2022.7.7 pytest-homeassistant-custom-component==0.10.8
run_next_test "strict"

pip3 install -qq homeassistant==2022.8.7 pytest-homeassistant-custom-component==0.11.12
run_next_test "strict"

pip3 install -qq homeassistant==2022.9.7 pytest-homeassistant-custom-component==0.11.26
run_next_test "strict"

pip3 install -qq homeassistant==2022.10.5 pytest-homeassistant-custom-component==0.12.10
run_next_test "strict"

pip3 install -qq homeassistant==2022.11.4 pytest-homeassistant-custom-component==0.12.21
run_next_test "strict"

pip3 install -qq homeassistant==2022.12.8 pytest-homeassistant-custom-component==0.12.36
run_next_test "auto"

pip3 install -qq homeassistant==2023.1.7 pytest-homeassistant-custom-component==0.12.49
run_next_test "auto"

# As of HA 2023.2, Python 3.9 is not supported.
