#!/usr/bin/env bash

# https://github.com/home-assistant/core
# https://github.com/MatthewFlamm/pytest-homeassistant-custom-component

# echo
# pip3 install homeassistant~=2022.6.0 pytest-homeassistant-custom-component~=0.9.0
# pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
# pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
# pytest -q --no-summary --asyncio-mode=strict tests
# This test fails!

echo
pip3 install -qq homeassistant==2022.7.0 pytest-homeassistant-custom-component==0.10.2
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=strict tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2022.7.7 pytest-homeassistant-custom-component==0.10.8
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=strict tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2022.8.7 pytest-homeassistant-custom-component==0.11.12
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=strict tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2022.9.7 pytest-homeassistant-custom-component==0.11.26
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=strict tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2022.10.5 pytest-homeassistant-custom-component==0.12.10
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=strict tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2022.11.4 pytest-homeassistant-custom-component==0.12.21
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=strict tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2022.12.8 pytest-homeassistant-custom-component==0.12.36
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

echo
pip3 install -qq homeassistant==2023.1.7 pytest-homeassistant-custom-component==0.12.49
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

# As of HA 2023.2, Python 3.9 is not supported.
echo
pip3 install -qq homeassistant==2023.2.5 pytest-homeassistant-custom-component==0.12.57
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed

# As of HA 2023.3, Python 3.11 is supported.
echo
pip3 install -qq homeassistant==2023.3.1 pytest-homeassistant-custom-component==0.13.5
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary --asyncio-mode=auto tests 2>&1 | grep passed
