#!/usr/bin/env bash

set -e

sudo chown -R vscode:vscode /workspaces

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements_dev.txt
python3 -m pip install --requirement requirements_test.txt