name: Publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main
      - master

jobs:
  release_zip_file:
    name: Publish zip file asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: 🛠️ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 🔢 Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: 🔢 Set version number
        run: |
          python3 ${{ github.workspace }}/scripts/update_manifest.py --version ${{ steps.version.outputs.version }}
          bash ${{ github.workspace }}/scripts/update_const ${{ steps.version.outputs.version }}

      - name: 📤 Upload zip to action
        uses: actions/upload-artifact@v3.1.3
        if: ${{ github.event_name == 'push' }}
        with:
          name: ev_smart_charging
          path: ${{ github.workspace }}/custom_components/ev_smart_charging

      # Pack the dir as a zip and upload to the release
      - name: 📦 ZIP Dir
        if: ${{ github.event_name == 'release' }}
        run: |
          cd ${{ github.workspace }}/custom_components/ev_smart_charging
          zip ev_smart_charging.zip -r ./

      - name: 📤 Upload zip to release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: ${{ github.workspace }}/custom_components/ev_smart_charging/ev_smart_charging.zip