#!/usr/bin/env bash

# echo
# pip3 install homeassistant~=2022.6.0 pytest-homeassistant-custom-component~=0.9.0
# pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
# pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
# pytest -q --no-summary tests
# This test fails!

echo
pip3 install -qq homeassistant==2022.7.0 pytest-homeassistant-custom-component==0.10.2
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary tests

echo
pip3 install -qq homeassistant==2022.7.7 pytest-homeassistant-custom-component==0.10.8
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary tests

echo
pip3 install -qq homeassistant==2022.8.7 pytest-homeassistant-custom-component==0.11.12
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary tests

echo
pip3 install -qq homeassistant==2022.9.7 pytest-homeassistant-custom-component==0.11.26
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary tests

echo
pip3 install -qq homeassistant==2022.10.5 pytest-homeassistant-custom-component==0.12.10
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary tests

echo
pip3 install -qq homeassistant~=2022.11.0 pytest-homeassistant-custom-component~=0.12.0
pip3 list 2>/dev/null | grep homeassistant | grep -v "\-home"
pip3 list 2>/dev/null | grep pytest-homeassistant-custom-component
pytest -q --no-summary tests
